### ISSUE TITLE
Lunar Client for Debian 11 / Bullseye

### ISSUE THREAD

**Issue by Kolpixx** [piware14/pi-ware#55]
What's your pi-ware version? (run ``cat $HOME/.local/share/pi-ware/version``)

Pi-Ware Version: 3f8b0095faed35384b1ef89077bc9e96af5b06bf

What's the bug you are experiencing?

If i install Lunar Client and open it only the black screen appears then it's crashing. I think its because Raspberry Pi OS had a new update to Debian 11 with Bullseye.

Here is the log:

```
pi@raspberrypi:~/pi-ware/store $ /home/pi/lunarclient-2.8.0-armv7l.AppImage
(node:3853) DeprecationWarning: file property is deprecated and will be removed in v5.
(Use `lunarclient --trace-deprecation ...` to show where the warning was created)
22:23:02.539 › Starting IPC server.
22:23:02.553 › Started IPC server.
22:23:03.580 (autoUpdater) › Checking for update
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0403
22:23:04.581 (autoUpdater) › Error: HttpError: 404 
"method: GET url: https://github.com/LunarClient/Launcher/releases.atom\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n"
Headers: {
  "server": "GitHub.com",
  "date": "Wed, 10 Nov 2021 21:23:04 GMT",
  "content-type": "text/plain; charset=utf-8",
  "vary": "X-PJAX, X-PJAX-Container, Accept-Encoding, Accept, X-Requested-With",
  "permissions-policy": "interest-cohort=()",
  "cache-control": "no-cache",
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "x-frame-options": "deny",
  "x-content-type-options": "nosniff",
  "x-xss-protection": "0",
  "referrer-policy": "origin-when-cross-origin, strict-origin-when-cross-origin",
  "expect-ct": "max-age=2592000, report-uri=\"https://api.github.com/_private/browser/errors\"",
  "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
  "content-encoding": "gzip",
  "set-cookie": [
    "_gh_sess=ltl3L8RrwHD3e4oG6uvFoez1fpJLIfTzh%2FasBxRrr6a%2FOe4P38o%2Fr9PhXB5Byj6yksBshU%2BgTC54QqO9MT2nSsGAngphq0DIgQbZlN3B3EgCWkhdP05%2Bks4REWecHS2lLsF1jvKFSeriOiw%2FtYlmv8yJu8HNmYXyAT4ZhgNOUbXqU6XqcZCB%2FgzDEX%2BQGcoTHh9M%2F7bPDX6LyvXGWndVBgKo8iM3AhHZTXW%2FXGsUeCpuEmmDrc%2FHRRXTuOWKLq27z%2FRIrAKm13uv6di2IcOhCg%3D%3D--oAGo%2Bbytyz5DosZk--S1T8Dj1G5FVr3%2BCaZKqHwg%3D%3D; Path=/; HttpOnly; Secure; SameSite=Lax",
    "_octo=GH1.1.1835668814.1636579384; Path=/; Domain=github.com; Expires=Thu, 10 Nov 2022 21:23:04 GMT; Secure; SameSite=Lax",
    "logged_in=no; Path=/; Domain=github.com; Expires=Thu, 10 Nov 2022 21:23:04 GMT; HttpOnly; Secure; SameSite=Lax"
  ],
  "content-length": "40",
  "x-github-request-id": "BE66:B82C:2198F65:236EED5:618C3838"
}
    at createHttpError (/tmp/.mount_lunarcyg9tlz/resources/app.asar/node_modules/builder-util-runtime/src/httpExecutor.ts:30:10)
    at ElectronHttpExecutor.handleResponse (/tmp/.mount_lunarcyg9tlz/resources/app.asar/node_modules/builder-util-runtime/src/httpExecutor.ts:143:9)
    at ClientRequest.<anonymous> (/tmp/.mount_lunarcyg9tlz/resources/app.asar/node_modules/builder-util-runtime/src/httpExecutor.ts:98:16)
    at ClientRequest.emit (events.js:315:20)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6816)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)
(node:3853) UnhandledPromiseRejectionWarning: HttpError: 404 
"method: GET url: https://github.com/LunarClient/Launcher/releases.atom\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n"
Headers: {
  "server": "GitHub.com",
  "date": "Wed, 10 Nov 2021 21:23:04 GMT",
  "content-type": "text/plain; charset=utf-8",
  "vary": "X-PJAX, X-PJAX-Container, Accept-Encoding, Accept, X-Requested-With",
  "permissions-policy": "interest-cohort=()",
  "cache-control": "no-cache",
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "x-frame-options": "deny",
  "x-content-type-options": "nosniff",
  "x-xss-protection": "0",
  "referrer-policy": "origin-when-cross-origin, strict-origin-when-cross-origin",
  "expect-ct": "max-age=2592000, report-uri=\"https://api.github.com/_private/browser/errors\"",
  "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
  "content-encoding": "gzip",
  "set-cookie": [
    "_gh_sess=ltl3L8RrwHD3e4oG6uvFoez1fpJLIfTzh%2FasBxRrr6a%2FOe4P38o%2Fr9PhXB5Byj6yksBshU%2BgTC54QqO9MT2nSsGAngphq0DIgQbZlN3B3EgCWkhdP05%2Bks4REWecHS2lLsF1jvKFSeriOiw%2FtYlmv8yJu8HNmYXyAT4ZhgNOUbXqU6XqcZCB%2FgzDEX%2BQGcoTHh9M%2F7bPDX6LyvXGWndVBgKo8iM3AhHZTXW%2FXGsUeCpuEmmDrc%2FHRRXTuOWKLq27z%2FRIrAKm13uv6di2IcOhCg%3D%3D--oAGo%2Bbytyz5DosZk--S1T8Dj1G5FVr3%2BCaZKqHwg%3D%3D; Path=/; HttpOnly; Secure; SameSite=Lax",
    "_octo=GH1.1.1835668814.1636579384; Path=/; Domain=github.com; Expires=Thu, 10 Nov 2022 21:23:04 GMT; Secure; SameSite=Lax",
    "logged_in=no; Path=/; Domain=github.com; Expires=Thu, 10 Nov 2022 21:23:04 GMT; HttpOnly; Secure; SameSite=Lax"
  ],
  "content-length": "40",
  "x-github-request-id": "BE66:B82C:2198F65:236EED5:618C3838"
}
    at createHttpError (/tmp/.mount_lunarcyg9tlz/resources/app.asar/node_modules/builder-util-runtime/src/httpExecutor.ts:30:10)
    at ElectronHttpExecutor.handleResponse (/tmp/.mount_lunarcyg9tlz/resources/app.asar/node_modules/builder-util-runtime/src/httpExecutor.ts:143:9)
    at ClientRequest.<anonymous> (/tmp/.mount_lunarcyg9tlz/resources/app.asar/node_modules/builder-util-runtime/src/httpExecutor.ts:98:16)
    at ClientRequest.emit (events.js:315:20)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6816)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)
(node:3853) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3853) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0403
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0403
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0403
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0403
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0403
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0403
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0403
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0403
[3853:1110/222306.226992:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
Trace/Breakpoint ausgelöst

```

How can we contact you?

Kolpix#1391

**Comment by gl91306** [comment]
join pi-ware discord [here](https://discord.gg/5KF4HKQGwt)

**Comment by gl91306** [comment]
this error is due to the new glibc thingy in bullseye, ill try and fix when i get home. my discord is PiKATchu#3939

**Comment by gl91306** [comment]
YO i found a temp fix. run the appimage with the --no-sandbox tag, so like `./lunarsomthing.AppImage --no-sandbox`

**Comment by gl91306** [comment]
closing for now. plz re-open if it dont work
